language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

#Build Environments
os: linux
dist: xenial

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  strategy: api
  api_key: $HEROKU_API_KEY
  edge: true
  app: devopslabfelipeeccel
  on:
      branch: main

      # provider: gae
      # keyfile: ../lab-devops-cloud-eccel-27e4cf17f687.json
      # project: lab-devops-cloud-eccel
      # on:
      # branch: main
